### ISSUE TITLE
Full name for composer suite helpers

### ISSUE THREAD

**Issue by souporserious** [hmans/composer-suite#349]
Curious if you would be ok with using the full names for some of the composer suite helpers like Sub, Mul, Div, etc? I was a little confused at first when seeing these in the examples. Happy to help with a PR for this if it sounds good :)

**Comment by hmans** [comment]
Hi, and thanks for opening the issue! I would prefer to not _rename_ these outright, but I think re-exporting under their full names (`Add`, `Subtract`, `Divide`, `Multiply`) would be fine. Were you thinking of any others on top of these ("etc.")?

A PR would be welcome, yes!

**Comment by souporserious** [comment]
Awesome! I put up a PR, I didn't notice anything else for short names. This is pure yak shaving, but one that stuck out was the use of `master`, would you be open to using `root` or `main` in these cases:

```tsx
const root = ShaderMaterialRoot({
  color: new Color("hotpink")
})
```

**Comment by hmans** [comment]
> Awesome! I put up a PR, I didn't notice anything else for short names. This is pure yak shaving, but one that stuck out was the use of `master`, would you be open to using `root` or `main` in these cases?

I'm open to renaming these (I suppose I didn't have one of my brightest days when picking this name), but it would obviously be a big breaking change. May I ask you to create a separate issue for this? I would be happy to schedule it for the next non-patch releases. ("Main" unit sounds fine!)

**Comment by souporserious** [comment]
Awesome, appreciate you considering the feedback! I made a follow-up issue [here](https://github.com/hmans/composer-suite/issues/352). I'm going to take a stab at building a JSX graph editor with composer suite so I've been deep in the docs, very exciting work!

**Comment by hmans** [comment]
Thank you! 🙏  Do keep me updated about that editor. The API for Shader Composer has a 100% focus on code-first use so far and may not be trivial to integrate into a visual tool (at the very least you'll probably need to wrap it in another layer of unit objects yourself.) For me personally, graphical node editors have not been a goal for this, but if the community comes up with something, I'd be excited to give it a go.
