### ISSUE TITLE
Rename "Master" Units

### ISSUE THREAD

**Issue by souporserious** [hmans/composer-suite#352]
Rename master instances to main:

```tsx
const root = ShaderMaterialMain({
  color: new Color("hotpink")
})
```

**Comment by hmans** [comment]
Seeing the code example you provided, I'm getting second thoughts about using "Main" as the new name. "ShaderMaterialMain" of what? Maybe "Root" does work better.

**Comment by souporserious** [comment]
Yeah, I like "root" nomenclature. But I'm also biased because you used that as variable names throughout some examples 😄

**Comment by hmans** [comment]
A little context: technically, any unit can be a root. The root is really just where compilation "begins", with the compiler assembling all the dependencies starting at the root unit. Other than that, the compiler doesn't really care what the root unit actually does in terms of GLSL.

The master units exist as glue between the wider API of the library, and specific ways to use GLSL. For example, `ShaderMaterialMaster` knows that it can write a color value into `gl_FragColor`. `CustomShaderMaterialMaster` knows that it can write into `csm_DiffuseColor`, `csm_Emissive`, and so on.

This sort of setup allows the largest part of the library to be agnostic of how and where it is actually used. Today, you can use it for Three.js and the various libraries that allow you to hook into its materials, but there is nothing stopping this library from being usable from other WebGL libraries (like PlayCanvas), or even with WebGL directly (at least ignoring the fact that it currently only produces GL ES version 100, where a lot of people would probably prefer 300; and of course let's now talk about WebGPU, which will require squeezing WGSL in there somehow. But it's definitely on the agenda!)
