### ISSUE TITLE
How to use vanilla

### ISSUE THREAD

**Issue by caramboleyo** [hmans/composer-suite#377]
How do you generate vanilla builds?

Vanilla means **plain** JavaScript, no TypeScript, no npm, no nodejs hosting it from the server.
Its a plain working file that runs in the browser.

Nothing i tried so far runs in the browser.

You modularized everything pretty well, it would be nice to keep that with (vanilla) esm builds.

**Comment by hmans** [comment]
Hi, and thanks for the issue. In the interest of keeping issues here actionable, I'm going to close this in favor of #378, which I just set up. For future questions, please use [Discussion](https://github.com/hmans/composer-suite/discussions).

Running these libraries in buildless environments has not been a focus so far, but should generally be possible (but might require some extra setup that I'll eventually look into.)

**Comment by caramboleyo** [comment]
Okay, i thought its just a command line command i wasnt aware of yet.
